server:
  port: 8080

spring:
  application:
    name: lets-play

  data:
    mongodb:
      uri: "mongodb://letsplay:letsplaypass@localhost:27017/lets_play?authSource=lets_play"
      auto-index-creation: true


logging:
  level:
    org.springframework.data.mongodb: INFO
